name: Close stale issues and PRs (reusable)

on:
  workflow_call:
    inputs:
      days-before-stale:
        type: number
        default: 30
      days-before-close:
        type: number
        default: 5
      exempt-pr-labels:
        type: string
        default: "dependencies"
      exempt-issue-labels:
        type: string
        default: "security,critical"
      exempt-milestones:
        type: string
        default: "future,alpha,beta"
      stale-issue-message:
        type: string
        default: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days."

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10
        with:
          stale-issue-message: ${{ inputs.stale-issue-message }}
          days-before-stale: ${{ inputs.days-before-stale }}
          days-before-close: ${{ inputs.days-before-close }}
          exempt-milestones: ${{ inputs.exempt-milestones }}
          exempt-pr-labels: ${{ inputs.exempt-pr-labels }}
          exempt-issue-labels: ${{ inputs.exempt-issue-labels }}
